# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE-BSD-Google file.

steps:
  - label: "clippy-x86-custom"
    commands:
    - cargo clippy --all-features --all-targets --workspace -- -D warnings
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
    - docker#v3.8.0:
       image: "rustvmm/dev:v12"
       always-pull: true
  - label: "test-vdpa"
    commands:
      - cargo test --features vhost-vdpa,vhost-kern vhost_kern::vdpa -- --nocapture
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
          devices: [ "/dev/vhost-vdpa-0" ]
