# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE-BSD-Google file.

steps:
  - label: "clippy-x86-custom"
    commands:
      - cargo clippy --all-features --all-targets --workspace -- -D warnings
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
  - label: "build-x86-vhost-kern"
    commands:
      - cargo build --features=vhost-kern
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
  - label: "build-x86-vhost-user-master"
    commands:
      - cargo build --features=vhost-user-master
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
  - label: "build-x86-vhost-user-slave"
    commands:
      - cargo build --features=vhost-user-slave
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
  - label: "clippy-x86-test"
    commands:
      - cargo test --features=vhost-kern,vhost-user-master,vhost-user-slave
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
  - label: "test-vdpa"
    commands:
      - cargo test --features vhost-vdpa,vhost-kern vhost_kern::vdpa -- --nocapture
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.8.0:
          image: "rustvmm/dev:v12"
          always-pull: true
          devices: [ "/dev/vhost-vdpa-0" ]
